server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-passenger
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0